language: generic
sudo: required
services:
    - docker
    
before_install:
    - docker build -t mcreach/test-docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true mcreach/test-docker-react npm run test -- --coverage